### PR TITLE
set_meta now working

### PR DESCRIPTION
**Pull request by hexdigest**
Hi, buddy!

You forgot to put bang after deep_merge! and as a result - set_meta didn't work and you couldn't override default settings with it.

### CODE REVIEW

**Comment by mcasimir** [comment]
Thank you! The problem wasn't that .. but now i've added some tests and fixed this bug also. Just released 0.2.0, i hope it is more robust and working as expected now.

**Comment by hexdigest** [comment]
Well, i'm pretty sure it was the reason. Bc you wanted set_meta to merge current options with the options that comes from hash and you need to use deep_merge!(bang) for that.

The simple test is to put set_meta right before meta_tags in the view. In old version it didn't work, with the bang it works.

**Comment by mcasimir** [comment]
Sure it was an issue! But i've had to change `@_meta_tags_hash` to `controller.instance_variable_get("@_meta_tags_hash")` also.

I don't know if it was related to some Rails 4 changes, maybe i should try to test in Rails 3 also.

**Comment by hexdigest** [comment]
I'm on Rails 3 still so I'll test it in few hours

2013/11/28 mcasimir notifications@github.com

**Comment by mcasimir** [comment]
Great thank you!

**Comment by hexdigest** [comment]
everything works perfectly

**Pull request merged**
